### PR TITLE
feat(grid): add total of all courses

### PR DESCRIPTION
**Pull request by Iliannnn**
The total is calculated by dividing the sum of earned points by the total possible points

image

### CODE REVIEW

**Comment by EbbDrop** [comment]
Thank you for the changes. It would be nice if you used the same formatting (2 instead of 4 spaces) to get a nicer diff.  Is it possible to reformat the changes?

**Comment by Iliannnn** [comment]
> Thank you for the changes. It would be nice if you used the same formatting (2 instead of 4 spaces) to get a nicer diff. Is it possible to reformat the changes?

Done.

**Comment by EbbDrop** [comment]
there seems to be a extra space on every line still

**Comment by Iliannnn** [comment]
> there seems to be a extra space on every line still

My bad, should be fixed now.

**Comment by EbbDrop** [comment]
Thank you again, I will publish a new version shortly

**Pull request merged**
